import { FormatAuraPipe } from "../../app/pipes/format-aura";
import { Achievement } from "../../app/services/achievements-manager";
import { COLLECTIBLES, RELICS } from "./collectibles";
import { BOSSES, BossId } from "./bosses";

export function createAchievements(
  getShopItems: () => any[],
  getTotalClicks: () => number,
  getTotalAura: () => number,
  getOutfitPieces: () => { unlocked: boolean }[] = () => [],
  getMaxedSkillCount: () => number = () => 0,
  getBackFacingReached: () => boolean = () => false,
  getRelicCount: () => number = () => 0,
  getGemsEarned: () => number = () => 0,
  getFigureCount: () => number = () => 0,
  isBossDefeated: (id: BossId) => boolean = () => false,
  getBossCount: () => number = () => 0
): Achievement[] {
  const achievements: Achievement[] = [
    {
      id: 1,
      title: "Aura Négative",
      description: "Frère ton aura est négative...",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() < 0,
      unlocked: false,
    },
        {
      id: 2,
      title: "Le début de quelque chose",
      description: "C'est un bon début",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() == 0,
      unlocked: false,
    },
    {
      id: 3,
      title: "Premiers Pas du Jawline Check",
      description: "Atteindre le niveau 5 avec Jawline Check.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[0]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 4,
      title: "Habitué du Jawline Check",
      description: "Atteindre le niveau 10 avec Jawline Check.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[0]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 5,
      title: "A l'aise avec le Jawline Check",
      description: "Atteindre le niveau 20 avec Jawline Check.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[0]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 6,
      title: "Exécution parfaite du Jawline Check",
      description: "Atteindre le niveau 50 avec Jawline Check.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[0]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 7,
      title: "Maîtrise incontestée du Jawline Check",
      description: "Atteindre le niveau 100 avec Jawline Check.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[0]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 8,
      title: "Début du Rizz",
      description: "Débloquer le Rizz.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[1]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 9,
      title: "Premiers Pas du Rizz",
      description: "Atteindre le niveau 5 avec Rizz.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[1]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 10,
      title: "Habitué du Rizz",
      description: "Atteindre le niveau 10 avec Rizz.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[1]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 11,
      title: "A l'aise avec le Rizz",
      description: "Atteindre le niveau 20 avec Rizz.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[1]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 12,
      title: "Exécution parfaite du Rizz",
      description: "Atteindre le niveau 50 avec Rizz.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[1]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 13,
      title: "Maîtrise incontestée du Rizz",
      description: "Atteindre le niveau 100 avec Rizz.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[1]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 14,
      title: "Début du Flex",
      description: "Débloquer le Biceps Flexing.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[2]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 15,
      title: "Premiers Pas du Biceps Flexing",
      description: "Atteindre le niveau 5 avec Biceps Flexing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[2]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 16,
      title: "Habitué du Biceps Flexing",
      description: "Atteindre le niveau 10 avec Biceps Flexing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[2]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 17,
      title: "A l'aise avec le Biceps Flexing",
      description: "Atteindre le niveau 20 avec Biceps Flexing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[2]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 18,
      title: "Exécution parfaite du Biceps Flexing",
      description: "Atteindre le niveau 50 avec Biceps Flexing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[2]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 19,
      title: "Maîtrise incontestée du Biceps Flexing",
      description: "Atteindre le niveau 100 avec Biceps Flexing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[2]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 20,
      title: "Début du Mewing",
      description: "Débloquer le Mewing.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[3]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 21,
      title: "Premiers Pas du Mewing",
      description: "Atteindre le niveau 5 avec Mewing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[3]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 22,
      title: "Habitué du Mewing",
      description: "Atteindre le niveau 10 avec Mewing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[3]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 23,
      title: "A l'aise avec le Mewing",
      description: "Atteindre le niveau 20 avec Mewing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[3]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 24,
      title: "Exécution parfaite du Mewing",
      description: "Atteindre le niveau 50 avec Mewing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[3]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 25,
      title: "Maîtrise incontestée du Mewing",
      description: "Atteindre le niveau 100 avec Mewing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[3]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 26,
      title: "Début du Silence Farming",
      description: "Débloquer le Silence Farming.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[4]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 27,
      title: "Premiers Pas du Silence Farming",
      description: "Atteindre le niveau 5 avec Silence Farming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[4]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 28,
      title: "Habitué du Silence Farming",
      description: "Atteindre le niveau 10 avec Silence Farming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[4]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 29,
      title: "A l'aise avec le Silence Farming",
      description: "Atteindre le niveau 20 avec Silence Farming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[4]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 30,
      title: "Exécution parfaite du Silence Farming",
      description: "Atteindre le niveau 50 avec Silence Farming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[4]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 31,
      title: "Maîtrise incontestée du Silence Farming",
      description: "Atteindre le niveau 100 avec Silence Farming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[4]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 32,
      title: "Début du Gaming",
      description: "Débloquer le Gaming.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[5]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 33,
      title: "Premiers Pas du Gaming",
      description: "Atteindre le niveau 5 avec Gaming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[5]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 34,
      title: "Habitué du Gaming",
      description: "Atteindre le niveau 10 avec Gaming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[5]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 35,
      title: "A l'aise avec le Gaming",
      description: "Atteindre le niveau 20 avec Gaming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[5]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 36,
      title: "Exécution parfaite du Gaming",
      description: "Atteindre le niveau 50 avec Gaming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[5]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 37,
      title: "Maîtrise incontestée du Gaming",
      description: "Atteindre le niveau 100 avec Gaming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[5]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 38,
      title: "Début des pets en public",
      description: "Débloquer le pet en public.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[6]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 39,
      title: "Premiers Pas des pets en public",
      description: "Atteindre le niveau 5 avec les pets en public.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[6]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 40,
      title: "Habitué des pets en public",
      description: "Atteindre le niveau 10 avec les pets en public.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[6]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 41,
      title: "A l'aise avec les pets en public",
      description: "Atteindre le niveau 20 avec les pets en public.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[6]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 42,
      title: "Exécution parfaite des pets en public",
      description: "Atteindre le niveau 50 avec les pets en public.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[6]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 43,
      title: "Maîtrise incontestée des pets en public",
      description: "Atteindre le niveau 100 avec les pets en public.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[6]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 44,
      title: "Début de la richesse",
      description: "Débloquer la monétisation de l'aura.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[7]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 45,
      title: "Premiers Pas de la richesse",
      description: "Atteindre le niveau 5 avec la monétisation de l'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[7]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 46,
      title: "Habitué de la richesse",
      description: "Atteindre le niveau 10 avec la monétisation de l'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[7]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 47,
      title: "A l'aise avec la richesse",
      description: "Atteindre le niveau 20 avec la monétisation de l'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[7]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 48,
      title: "Gros richou",
      description: "Atteindre le niveau 50 avec la monétisation de l'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[7]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 49,
      title: "Maîtrise incontestée de la richesse",
      description: "Atteindre le niveau 100 avec la monétisation de l'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[7]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 50,
      title: "Petit Bodybuilder",
      description: "Atteindre un total de 25 niveaux cumulés.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 25,
      unlocked: false,
    },
    {
      id: 51,
      title: "début du scaling",
      description: "Atteindre un total de 50 niveaux cumulés.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 50,
      unlocked: false,
    },
    {
      id: 52,
      title: "Scale acceptable",
      description: "Atteindre un total de 100 niveaux cumulés.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 100,
      unlocked: false,
    },
    {
      id: 53,
      title: "Scale honorable",
      description: "Atteindre un total de 250 niveaux cumulés.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 250,
      unlocked: false,
    },
    {
      id: 54,
      title: "Scale incroyable",
      description: "Atteindre un total de 500 niveaux cumulés.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 500,
      unlocked: false,
    },
    {
      id: 55,
      title: "Scale monstrueux",
      description: `Atteindre un total de ${new FormatAuraPipe().transform(1000)} niveaux cumulés.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 1000,
      unlocked: false,
    },
    {
      id: 56,
      title: "Noob Clicker",
      description: "Cliquer 10 fois au total.",
      icon: "assets/imgs/achievements/click_achievement.png",
      condition: () => getTotalClicks() >= 10,
      unlocked: false,
    },
    {
      id: 57,
      title: "Normal Clicker",
      description: "Cliquer 100 fois au total.",
      icon: "assets/imgs/achievements/click_achievement.png",
      condition: () => getTotalClicks() >= 100,
      unlocked: false,
    },
    {
      id: 58,
      title: "Click Machine",
      description: "Cliquer 500 fois au total.",
      icon: "assets/imgs/achievements/click_achievement.png",
      condition: () => getTotalClicks() >= 500,
      unlocked: false,
    },
        {
      id: 59,
      title: "Clickeur Fou",
      description: `Cliquer ${new FormatAuraPipe().transform(1500)} fois au total.`,
      icon: "assets/imgs/achievements/click_achievement.png",
      condition: () => getTotalClicks() >= 1500,
      unlocked: false,
    },
    {
      id: 60,
      title: "Click God",
      description: `Cliquer ${new FormatAuraPipe().transform(3000)} fois au total.`,
      icon: "assets/imgs/achievements/click_achievement.png",
      condition: () => getTotalClicks() >= 3000,
      unlocked: false,
    },
    {
      id: 61,
      title: "Capital d'Aura microscopique",
      description: `Générer ${new FormatAuraPipe().transform(1000)} d'aura au total.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() >= 1000,
      unlocked: false,
    },
    {
      id: 62,
      title: "Capital d'Aura en développement",
      description: `Générer ${new FormatAuraPipe().transform(10000)} d'aura au total.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() >= 10000,
      unlocked: false,
    },
    {
      id: 63,
      title: "Capital d'Aura en développement",
      description: `Générer ${new FormatAuraPipe().transform(100000)} d'aura au total.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() >= 100000,
      unlocked: false,
    },
    {
      id: 64,
      title: "Aura Millionaire",
      description: `Générer ${new FormatAuraPipe().transform(1000000)} d'aura au total.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() >= 1000000,
      unlocked: false,
    },
    {
      id: 65,
      title: "Aura Billionaire",
      description: `Générer ${new FormatAuraPipe().transform(1000000000)} d'aura au total.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() >= 1000000000,
      unlocked: false,
    },
    {
      id: 66,
      title: "Aura Trillionaire",
      description: `Générer ${new FormatAuraPipe().transform(1000000000000)} d'aura au total.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() >= 1000000000000,
      unlocked: false,
    },
    {
      id: 67,
      title: "Sigma Grindset",
      description: "Avoir tous les items débloqués.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().every(i => i?.level() >= 1),
      unlocked: false,
    },
    {
      id: 68,
      title: "Drip Naissant",
      description: "Débloquer une première pièce d'outfit pour le moyai.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getOutfitPieces().some(piece => piece.unlocked),
      unlocked: false,
    },
    {
      id: 69,
      title: "Drip Intégral",
      description: "Débloquer toutes les pièces d'outfit du moyai.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => {
        const pieces = getOutfitPieces();
        return pieces.length > 0 && pieces.every(piece => piece.unlocked);
      },
      unlocked: false,
    },
    {
      id: 70,
      title: "Maxxing",
      description: "Porter une compétence à son niveau maximal.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getMaxedSkillCount() >= 1,
      unlocked: false,
    },
    {
      id: 72,
      title: "Face B",
      description: "Contempler le dos du moyai pendant cinq secondes d'affilée.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getBackFacingReached(),
      unlocked: false,
    },
    {
      id: 71,
      title: "Full Maxxing",
      description: "Porter cinq compétences à leur niveau maximal.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getMaxedSkillCount() >= 5,
      unlocked: false,
    },
    {
      id: 73,
      title: "Première Pépite",
      description: "Trouver sa première gemme.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getGemsEarned() >= 1,
      unlocked: false,
    },
    {
      id: 74,
      title: "Prospecteur",
      description: "Amasser cent gemmes au total.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getGemsEarned() >= 100,
      unlocked: false,
    },
    {
      id: 75,
      title: "Filon Mère",
      description: "Amasser mille gemmes au total.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getGemsEarned() >= 1000,
      unlocked: false,
    },
    {
      id: 76,
      title: "Première Statuette",
      description: "Obtenir sa première statuette dans un coffre.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getFigureCount() >= 1,
      unlocked: false,
    },
    {
      id: 77,
      title: "Vitrine Garnie",
      description: "Réunir dix statuettes.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getFigureCount() >= 10,
      unlocked: false,
    },
    {
      id: 78,
      title: "Collection Complète",
      description: "Réunir toutes les statuettes du jeu.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getFigureCount() >= COLLECTIBLES.length,
      unlocked: false,
    },
    {
      id: 79,
      title: "Trouvaille Sacrée",
      description: "Mettre la main sur une relique sacrée de l'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getRelicCount() >= 1,
      unlocked: false,
    },
    {
      id: 80,
      title: "Reliquaire",
      description: "Réunir cinq reliques sacrées.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getRelicCount() >= 5,
      unlocked: false,
    },
    {
      id: 81,
      title: "Gardien des Reliques",
      description: "Réunir les dix reliques sacrées de l'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getRelicCount() >= RELICS.length,
      unlocked: false,
    },
    {
      id: 100,
      title: "Requin en Baskets",
      description: "Vaincre Tralalero Tralala en battle d'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => isBossDefeated('tralalero'),
      unlocked: false,
    },
    {
      id: 101,
      title: "Tung Tung Tung",
      description: "Vaincre Tung Tung Tung Sahur en battle d'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => isBossDefeated('sahur'),
      unlocked: false,
    },
    {
      id: 102,
      title: "Brr Brr",
      description: "Vaincre Brr Brr Patapim en battle d'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => isBossDefeated('patapim'),
      unlocked: false,
    },
    {
      id: 103,
      title: "Lirili Larila",
      description: "Vaincre Lirili Larila en battle d'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => isBossDefeated('lirili'),
      unlocked: false,
    },
    {
      id: 104,
      title: "Bombardement",
      description: "Vaincre Bombardiro Crocodilo en battle d'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => isBossDefeated('bombardiro'),
      unlocked: false,
    },
    {
      id: 105,
      title: "Namek",
      description: "Vaincre Piccolo en battle d'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => isBossDefeated('piccolo'),
      unlocked: false,
    },
    {
      id: 106,
      title: "Succession",
      description: "Vaincre son frère Chad Moai et reprendre l'héritage.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => isBossDefeated('chad'),
      unlocked: false,
    },
    {
      id: 120,
      title: "Chasseur de Brainrots",
      description: "Vaincre la moitié des boss des battles d'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getBossCount() >= Math.ceil(BOSSES.length / 2),
      unlocked: false,
    },
    {
      id: 121,
      title: "Aura Suprême",
      description: "Vaincre tous les boss des battles d'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getBossCount() >= BOSSES.length,
      unlocked: false,
    }
  ];

  for (let i = 0; i <= achievements.length - 1; i++) {
    if(achievements[i]){
      achievements[i].id = i;
    }
  }

  return achievements;
}
