import { FormatAuraPipe } from "../../app/pages/game-page/game-page";
import { Achievement } from "../../app/services/achievements-manager";

export function createAchievements(
  getShopItems: () => any[],
  getTotalClicks: () => number,
  getTotalAura: () => number
): Achievement[] {
  const achievements: Achievement[] = [
    {
      id: 0,
      title: "Aura Négative",
      description: "Frère ton aura est négative...",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() < 0,
      unlocked: false,
    },
        {
      id: 0,
      title: "Le début de quelque chose",
      description: "C'est un bon début",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() == 0,
      unlocked: false,
    },
    {
      id: 0,
      title: "Premiers Pas du Jawline Check",
      description: "Atteindre le niveau 5 avec Jawline Check.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[0]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 0,
      title: "Habitué du Jawline Check",
      description: "Atteindre le niveau 10 avec Jawline Check.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[0]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 0,
      title: "A l'aise avec le Jawline Check",
      description: "Atteindre le niveau 20 avec Jawline Check.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[0]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 0,
      title: "Exécution parfaite du Jawline Check",
      description: "Atteindre le niveau 50 avec Jawline Check.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[0]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 0,
      title: "Maîtrise incontestée du Jawline Check",
      description: "Atteindre le niveau 100 avec Jawline Check.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[0]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 0,
      title: "Début du Rizz",
      description: "Débloquer le Rizz.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[1]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 0,
      title: "Premiers Pas du Rizz",
      description: "Atteindre le niveau 5 avec Rizz.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[1]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 0,
      title: "Habitué du Rizz",
      description: "Atteindre le niveau 10 avec Rizz.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[1]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 0,
      title: "A l'aise avec le Rizz",
      description: "Atteindre le niveau 20 avec Rizz.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[1]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 0,
      title: "Exécution parfaite du Rizz",
      description: "Atteindre le niveau 50 avec Rizz.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[1]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 0,
      title: "Maîtrise incontestée du Rizz",
      description: "Atteindre le niveau 100 avec Rizz.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[1]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 0,
      title: "Début du Flex",
      description: "Débloquer le Biceps Flexing.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[2]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 0,
      title: "Premiers Pas du Biceps Flexing",
      description: "Atteindre le niveau 5 avec Biceps Flexing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[2]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 0,
      title: "Habitué du Biceps Flexing",
      description: "Atteindre le niveau 10 avec Biceps Flexing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[2]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 0,
      title: "A l'aise avec le Biceps Flexing",
      description: "Atteindre le niveau 20 avec Biceps Flexing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[2]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 0,
      title: "Exécution parfaite du Biceps Flexing",
      description: "Atteindre le niveau 50 avec Biceps Flexing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[2]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 0,
      title: "Maîtrise incontestée du Biceps Flexing",
      description: "Atteindre le niveau 100 avec Biceps Flexing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[2]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 0,
      title: "Début du Mewing",
      description: "Débloquer le Mewing.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[3]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 0,
      title: "Premiers Pas du Mewing",
      description: "Atteindre le niveau 5 avec Mewing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[3]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 0,
      title: "Habitué du Mewing",
      description: "Atteindre le niveau 10 avec Mewing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[3]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 0,
      title: "A l'aise avec le Mewing",
      description: "Atteindre le niveau 20 avec Mewing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[3]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 0,
      title: "Exécution parfaite du Mewing",
      description: "Atteindre le niveau 50 avec Mewing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[3]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 0,
      title: "Maîtrise incontestée du Mewing",
      description: "Atteindre le niveau 100 avec Mewing.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[3]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 0,
      title: "Début du Silence Farming",
      description: "Débloquer le Silence Farming.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[4]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 0,
      title: "Premiers Pas du Silence Farming",
      description: "Atteindre le niveau 5 avec Silence Farming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[4]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 0,
      title: "Habitué du Silence Farming",
      description: "Atteindre le niveau 10 avec Silence Farming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[4]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 0,
      title: "A l'aise avec le Silence Farming",
      description: "Atteindre le niveau 20 avec Silence Farming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[4]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 0,
      title: "Exécution parfaite du Silence Farming",
      description: "Atteindre le niveau 50 avec Silence Farming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[4]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 0,
      title: "Maîtrise incontestée du Silence Farming",
      description: "Atteindre le niveau 100 avec Silence Farming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[4]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 0,
      title: "Début du Gaming",
      description: "Débloquer le Gaming.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[5]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 0,
      title: "Premiers Pas du Gaming",
      description: "Atteindre le niveau 5 avec Gaming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[5]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 0,
      title: "Habitué du Gaming",
      description: "Atteindre le niveau 10 avec Gaming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[5]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 0,
      title: "A l'aise avec le Gaming",
      description: "Atteindre le niveau 20 avec Gaming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[5]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 0,
      title: "Exécution parfaite du Gaming",
      description: "Atteindre le niveau 50 avec Gaming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[5]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 0,
      title: "Maîtrise incontestée du Gaming",
      description: "Atteindre le niveau 100 avec Gaming.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[5]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 0,
      title: "Début des pets en public",
      description: "Débloquer le pet en public.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[6]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 0,
      title: "Premiers Pas des pets en public",
      description: "Atteindre le niveau 5 avec les pets en public.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[6]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 0,
      title: "Habitué des pets en public",
      description: "Atteindre le niveau 10 avec les pets en public.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[6]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 0,
      title: "A l'aise avec les pets en public",
      description: "Atteindre le niveau 20 avec les pets en public.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[6]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 0,
      title: "Exécution parfaite des pets en public",
      description: "Atteindre le niveau 50 avec les pets en public.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[6]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 0,
      title: "Maîtrise incontestée des pets en public",
      description: "Atteindre le niveau 100 avec les pets en public.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[6]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 0,
      title: "Début de la richesse",
      description: "Débloquer la monétisation de l'aura.",
      icon: "assets/imgs/achievements/unlocked_achievement.png",
      condition: () => getShopItems()[7]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 0,
      title: "Premiers Pas de la richesse",
      description: "Atteindre le niveau 5 avec la monétisation de l'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[7]?.level() >= 5,
      unlocked: false,
    },
        {
      id: 0,
      title: "Habitué de la richesse",
      description: "Atteindre le niveau 10 avec la monétisation de l'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[7]?.level() >= 10,
      unlocked: false,
    },
        {
      id: 0,
      title: "A l'aise avec la richesse",
      description: "Atteindre le niveau 20 avec la monétisation de l'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[7]?.level() >= 20,
      unlocked: false,
    },
        {
      id: 0,
      title: "Gros richou",
      description: "Atteindre le niveau 50 avec la monétisation de l'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[7]?.level() >= 50,
      unlocked: false,
    },
    {
      id: 0,
      title: "Maîtrise incontestée de la richesse",
      description: "Atteindre le niveau 100 avec la monétisation de l'aura.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems()[7]?.level() >= 100,
      unlocked: false,
    },
    {
      id: 0,
      title: "Petit Bodybuilder",
      description: "Atteindre un total de 25 niveaux cumulés.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 25,
      unlocked: false,
    },
    {
      id: 0,
      title: "début du scaling",
      description: "Atteindre un total de 50 niveaux cumulés.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 50,
      unlocked: false,
    },
    {
      id: 0,
      title: "Scale acceptable",
      description: "Atteindre un total de 100 niveaux cumulés.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 100,
      unlocked: false,
    },
    {
      id: 0,
      title: "Scale honorable",
      description: "Atteindre un total de 250 niveaux cumulés.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 250,
      unlocked: false,
    },
    {
      id: 0,
      title: "Scale incroyable",
      description: "Atteindre un total de 500 niveaux cumulés.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 500,
      unlocked: false,
    },
    {
      id: 0,
      title: "Scale monstrueux",
      description: `Atteindre un total de ${new FormatAuraPipe().transform(1000)} niveaux cumulés.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 1000,
      unlocked: false,
    },
    {
      id: 0,
      title: "Noob Clicker",
      description: "Cliquer 10 fois au total.",
      icon: "assets/imgs/achievements/click_achievement.png",
      condition: () => getTotalClicks() >= 10,
      unlocked: false,
    },
    {
      id: 0,
      title: "Normal Clicker",
      description: "Cliquer 100 fois au total.",
      icon: "assets/imgs/achievements/click_achievement.png",
      condition: () => getTotalClicks() >= 100,
      unlocked: false,
    },
    {
      id: 0,
      title: "Click Machine",
      description: "Cliquer 500 fois au total.",
      icon: "assets/imgs/achievements/click_achievement.png",
      condition: () => getTotalClicks() >= 500,
      unlocked: false,
    },
        {
      id: 0,
      title: "Clickeur Fou",
      description: `Cliquer ${new FormatAuraPipe().transform(1500)} fois au total.`,
      icon: "assets/imgs/achievements/click_achievement.png",
      condition: () => getTotalClicks() >= 1500,
      unlocked: false,
    },
    {
      id: 0,
      title: "Click God",
      description: `Cliquer ${new FormatAuraPipe().transform(3000)} fois au total.`,
      icon: "assets/imgs/achievements/click_achievement.png",
      condition: () => getTotalClicks() >= 3000,
      unlocked: false,
    },
    {
      id: 0,
      title: "Capital d'Aura microscopique",
      description: `Générer ${new FormatAuraPipe().transform(1000)} d'aura au total.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() >= 1000,
      unlocked: false,
    },
    {
      id: 0,
      title: "Capital d'Aura en développement",
      description: `Générer ${new FormatAuraPipe().transform(10000)} d'aura au total.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() >= 10000,
      unlocked: false,
    },
    {
      id: 0,
      title: "Capital d'Aura en développement",
      description: `Générer ${new FormatAuraPipe().transform(100000)} d'aura au total.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() >= 100000,
      unlocked: false,
    },
    {
      id: 0,
      title: "Aura Millionaire",
      description: `Générer ${new FormatAuraPipe().transform(1000000)} d'aura au total.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() >= 1000000,
      unlocked: false,
    },
    {
      id: 0,
      title: "Aura Billionaire",
      description: `Générer ${new FormatAuraPipe().transform(1000000000)} d'aura au total.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() >= 1000000000,
      unlocked: false,
    },
    {
      id: 0,
      title: "Aura Trillionaire",
      description: `Générer ${new FormatAuraPipe().transform(1000000000000)} d'aura au total.`,
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getTotalAura() >= 1000000000000,
      unlocked: false,
    },
    {
      id: 0,
      title: "Sigma Grindset",
      description: "Avoir tous les items débloqués.",
      icon: "assets/imgs/achievements/trophy_achievement.png",
      condition: () => getShopItems().every(i => i?.level() >= 1),
      unlocked: false,
    }
  ];

  for (let i = 0; i <= achievements.length - 1; i++) {
    if(achievements[i]){
      achievements[i].id = i;
    }
  }

  return achievements;
}
