import { Achievement } from "../../app/services/achievements-manager";

export function createAchievements(
  getShopItems: () => any[],
  getTotalClicks: () => number,
  getTotalAura: () => number
): Achievement[] {
  return [
    {
      id: 1,
      title: "Premiers Pas",
      description: "Atteindre le niveau 1 avec Jawline Check.",
      icon: "assets/imgs/achievements/step1.png",
      condition: () => getShopItems()[0]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 2,
      title: "Début du Rizz",
      description: "Débloquer l'item Rizz.",
      icon: "assets/imgs/achievements/rizz.png",
      condition: () => getShopItems()[1]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 3,
      title: "Flex Légendaire",
      description: "Atteindre le niveau 5 de Biceps Flexing.",
      icon: "assets/imgs/achievements/biceps.png",
      condition: () => getShopItems()[2]?.level() >= 5,
      unlocked: false,
    },
    {
      id: 4,
      title: "Mewing Découvrez",
      description: "Débloquer l'item Mewing.",
      icon: "assets/imgs/achievements/mewing.png",
      condition: () => getShopItems()[3]?.level() >= 1,
      unlocked: false,
    },
    {
      id: 5,
      title: "Petit Bodybuilder",
      description: "Atteindre un total de 20 niveaux cumulés.",
      icon: "assets/imgs/achievements/total_levels.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 20,
      unlocked: false,
    },
    {
      id: 6,
      title: "Ascension",
      description: "Atteindre un total de 100 niveaux cumulés.",
      icon: "assets/imgs/achievements/ascension.png",
      condition: () => getShopItems().reduce((acc, i) => acc + i.level(), 0) >= 100,
      unlocked: false,
    },
    {
      id: 7,
      title: "Click Machine",
      description: "Cliquer 500 fois au total.",
      icon: "assets/imgs/achievements/clicks.png",
      condition: () => getTotalClicks() >= 500,
      unlocked: false,
    },
    {
      id: 8,
      title: "Click God",
      description: "Cliquer 5000 fois au total.",
      icon: "assets/imgs/achievements/clicks_god.png",
      condition: () => getTotalClicks() >= 5000,
      unlocked: false,
    },
    {
      id: 9,
      title: "Aura Collector",
      description: "Générer 1000 d'aura au total.",
      icon: "assets/imgs/achievements/aura.png",
      condition: () => getTotalAura() >= 1000,
      unlocked: false,
    },
    {
      id: 10,
      title: "Aura Millionaire",
      description: "Générer 1 000 000 d'aura au total.",
      icon: "assets/imgs/achievements/aura_million.png",
      condition: () => getTotalAura() >= 1000000,
      unlocked: false,
    },
    {
      id: 11,
      title: "Rizzler Suprême",
      description: "Avoir Rizz au niveau 10.",
      icon: "assets/imgs/achievements/rizzler.png",
      condition: () => getShopItems()[1]?.level() >= 10,
      unlocked: false,
    },
    {
      id: 12,
      title: "Sigma Grindset",
      description: "Avoir tous les items débloqués.",
      icon: "assets/imgs/achievements/sigma.png",
      condition: () => getShopItems().every(i => i?.level() >= 1),
      unlocked: false,
    },
    {
      id: 13,
      title: "Strongest NPC",
      description: "Avoir Biceps Flexing niveau 20.",
      icon: "assets/imgs/achievements/strongest.png",
      condition: () => getShopItems()[2]?.level() >= 20,
      unlocked: false,
    },
    {
      id: 14,
      title: "Chad Ascension",
      description: "Avoir Mewing niveau 25.",
      icon: "assets/imgs/achievements/chad.png",
      condition: () => getShopItems()[3]?.level() >= 25,
      unlocked: false,
    },
    {
      id: 15,
      title: "Aura Overlord",
      description: "Monetize Aura niveau 10 ou plus.",
      icon: "assets/imgs/achievements/aura_overlord.png",
      condition: () => getShopItems()[7]?.level() >= 10,
      unlocked: false,
    }
  ];
}
